# Formula 1 Dataset Cleaning

## Data Cleaning Process

Files Covered: pitStops.csv to status.csv

This notebook contains the data cleaning procedures applied to the assigned Formula 1 datasets, including handling missing values, removing duplicates, correcting data types, and preparing the files for analysis.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving pitStops.csv to pitStops (2).csv
Saving qualifying.csv to qualifying (2).csv
Saving races.csv to races (2).csv
Saving results.csv to results (2).csv
Saving seasons.csv to seasons (2).csv
Saving status.csv to status (2).csv

## Import Libraries

In [ ]:
import pandas as pd
import numpy as np

## Load CSV Files

In [ ]:
pit = pd.read_csv("pitStops.csv")
qual = pd.read_csv("qualifying.csv")
races = pd.read_csv("races.csv")
results = pd.read_csv("results.csv")
seasons = pd.read_csv("seasons.csv")
status = pd.read_csv("status.csv")

## Cleaning pitStops.csv

This section performs data cleaning and preprocessing for the pitStops dataset. The file contains Formula 1 pit stop records including race ID, driver ID, lap number, stop number, stop time, duration, and milliseconds.

In [176]:
pit.head()

   raceId  driverId  stop  lap      time  duration  milliseconds
0     841       153     1    1  17:05:23    26.898         26898
1     841        30     1    1  17:05:52    25.021         25021
2     841        17     1   11  17:20:48    23.426         23426
3     841         4     1   12  17:22:34    23.251         23251
4     841        13     1   13  17:24:10    23.842         23842

In [177]:
pit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6251 entries, 0 to 6250
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   raceId        6251 non-null   int64
 1   driverId      6251 non-null   int64
 2   stop          6251 non-null   int64
 3   lap           6251 non-null   int64
 4   time          6251 non-null   object
 5   duration      6251 non-null   float64
 6   milliseconds  6251 non-null   int64
dtypes: float64(1), int64(5), object(1)
memory usage: 342.0+ KB

In [178]:
pit.isnull().sum()

raceId          0
driverId        0
stop            0
lap             0
time            0
duration        0
milliseconds    0
dtype: int64

In [179]:
pit.duplicated().sum()

np.int64(0)

### Cleaning Process

The dataset contains no missing values and no duplicate records. Additional preprocessing is applied to standardize column names and convert data types for consistency.

In [180]:
# Clean column names
pit.columns = pit.columns.str.strip()

# Remove duplicate rows
pit.drop_duplicates(inplace=True)

# Handle missing values
# Text columns
for col in pit.select_dtypes(include='object').columns:
    pit[col].fillna("Unknown", inplace=True)

# Numeric columns
for col in pit.select_dtypes(include=['int64', 'float64']).columns:
    pit[col].fillna(pit[col].median(), inplace=True)

# Convert time column
pit['time'] = pd.to_datetime(pit['time'], format='%H:%M:%S', errors='coerce').dt.time

# Convert duration column
pit['duration'] = pd.to_numeric(pit['duration'], errors='coerce')

# Convert integer columns
pit['raceId'] = pit['raceId'].astype(int)
pit['driverId'] = pit['driverId'].astype(int)
pit['stop'] = pit['stop'].astype(int)
pit['lap'] = pit['lap'].astype(int)
pit['milliseconds'] = pit['milliseconds'].astype(int)

pit.head()

/tmp/ipykernel_3731/4204691547.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pit[col].fillna("Unknown", inplace=True)
/tmp/ipykernel_3731/4204691547.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pit[col].fillna(pit[col].median(), inplace=True)

   raceId  driverId  stop  lap      time  duration  milliseconds
0     841       153     1    1  17:05:23    26.898         26898
1     841        30     1    1  17:05:52    25.021         25021
2     841        17     1   11  17:20:48    23.426         23426
3     841         4     1   12  17:22:34    23.251         23251
4     841        13     1   13  17:24:10    23.842         23842

In [182]:
pit.info()
pit.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6251 entries, 0 to 6250
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   raceId        6251 non-null   int64
 1   driverId      6251 non-null   int64
 2   stop          6251 non-null   int64
 3   lap           6251 non-null   int64
 4   time          6251 non-null   object
 5   duration      6251 non-null   float64
 6   milliseconds  6251 non-null   int64
dtypes: float64(1), int64(5), object(1)
memory usage: 342.0+ KB

,raceId,driverId,stop,lap,duration,milliseconds
count,6251.000000,6251.000000,6251.000000,6251.000000,6251.000000,6.251000e+03
mean,907.860342,429.468245,1.836346,24.813470,24.124340,4.774453e+04
std,44.327698,397.079565,0.935314,14.150022,4.322857,1.791970e+05
min,841.000000,1.000000,1.000000,1.000000,12.897000,1.289700e+04
25%,868.000000,13.000000,1.000000,13.000000,21.768000,2.176800e+04
50%,902.000000,807.000000,2.000000,24.000000,23.263000,2.334000e+04
75%,950.000000,821.000000,2.000000,35.000000,25.277500,2.554700e+04
max,988.000000,843.000000,6.000000,74.000000,59.555000,2.011266e+06

### Result

The pitStops dataset has been successfully cleaned and standardized. It is now ready for merging, visualization, and further analysis.

## Cleaning qualifying.csv

This section performs data cleaning and preprocessing for the qualifying dataset. The file contains Formula 1 qualifying session records including qualifying positions, drivers, constructors, and lap times (Q1, Q2, Q3).

In [183]:
qual.head()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

In [ ]:
qual.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7516 entries, 0 to 7515
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qualifyId      7516 non-null   int64
 1   raceId         7516 non-null   int64
 2   driverId       7516 non-null   int64
 3   constructorId  7516 non-null   int64
 4   number         7516 non-null   int64
 5   position       7516 non-null   int64
 6   q1             7397 non-null   object
 7   q2             3652 non-null   object
 8   q3             2178 non-null   object
dtypes: int64(6), object(3)
memory usage: 528.6+ KB

In [ ]:
qual.isnull().sum()

qualifyId           0
raceId              0
driverId            0
constructorId       0
number              0
position            0
q1                119
q2               3864
q3               5338
dtype: int64

In [ ]:
qual.duplicated().sum()

np.int64(0)

### Cleaning Process

The dataset is checked for missing values, duplicate records, inconsistent column names, and incorrect data types. Missing qualifying times are expected for drivers who did not advance to later sessions.

In [ ]:
# Clean column names
qual.columns = qual.columns.str.strip()

# Remove duplicate rows
qual.drop_duplicates(inplace=True)

# Fill missing qualifying times
qual['q1'] = qual['q1'].astype(str).str.strip().fillna("No Time")
qual['q2'] = qual['q2'].astype(str).str.strip().fillna("No Time")
qual['q3'] = qual['q3'].astype(str).str.strip().fillna("No Time")

# Convert numeric columns
qual['qualifyId'] = qual['qualifyId'].astype(int)
qual['raceId'] = qual['raceId'].astype(int)
qual['driverId'] = qual['driverId'].astype(int)
qual['constructorId'] = qual['constructorId'].astype(int)
qual['number'] = qual['number'].astype(int)
qual['position'] = qual['position'].astype(int)

qual.head()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

In [ ]:
qual.info()
qual.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7516 entries, 0 to 7515
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qualifyId      7516 non-null   int64
 1   raceId         7516 non-null   int64
 2   driverId       7516 non-null   int64
 3   constructorId  7516 non-null   int64
 4   number         7516 non-null   int64
 5   position       7516 non-null   int64
 6   q1             7516 non-null   object
 7   q2             7516 non-null   object
 8   q3             7516 non-null   object
dtypes: int64(6), object(3)
memory usage: 528.6+ KB

,qualifyId,raceId,driverId,constructorId,number,position
count,7516.000000,7516.000000,7516.000000,7516.000000,7516.000000,7516.000000
mean,3762.934939,449.830894,203.803752,34.757318,15.288318,11.473523
std,2175.400371,384.012280,325.034734,61.700784,14.057586,6.424936
min,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
25%,1879.750000,91.000000,14.000000,4.000000,7.000000,6.000000
50%,3759.500000,259.000000,30.000000,9.000000,12.000000,11.000000
75%,5639.250000,887.000000,111.000000,19.000000,20.000000,17.000000
max,7539.000000,988.000000,843.000000,210.000000,99.000000,28.000000

### Result

The qualifying dataset has been successfully cleaned and standardized. Missing lap times were handled appropriately, duplicate rows were removed, and column formats were corrected. The dataset is now ready for analysis and visualization.

## Cleaning races.csv

This section performs data cleaning and preprocessing for the races dataset. The file contains Formula 1 race event information including season year, round number, circuit, race name, race date, time, and related session schedules.

In [ ]:
races.head()

,raceId,year,round,circuitId,name,date,time,url
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...

In [ ]:
races.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   raceId     997 non-null    int64
 1   year       997 non-null    int64
 2   round      997 non-null    int64
 3   circuitId  997 non-null    int64
 4   name       997 non-null    object
 5   date       997 non-null    object
 6   time       266 non-null    object
 7   url        997 non-null    object
dtypes: int64(4), object(4)
memory usage: 62.4+ KB

In [ ]:
races.isnull().sum()

raceId       0
year         0
round        0
circuitId    0
name         0
date         0
time         0
url          0
dtype: int64

In [ ]:
races.duplicated().sum()

np.int64(0)

### Cleaning Process

The dataset is checked for missing values, duplicate rows, incorrect data types, and inconsistent formatting. Date and time columns are converted into proper datetime format for easier analysis.

In [ ]:
# Clean column names
races.columns = races.columns.str.strip()

# Remove duplicate rows
races.drop_duplicates(inplace=True)

# Fill missing text values
races['name'] = races['name'].fillna("Unknown").str.strip()
races['url'] = races['url'].fillna("Unknown").str.strip()

# Convert date column
races['date'] = pd.to_datetime(races['date'].astype(str).str.strip(), errors='coerce')

# Handle all null values in time column
races['time'] = races['time'].fillna("Unknown").astype(str).str.strip()

# Convert numeric columns
races['raceId'] = races['raceId'].astype(int)
races['year'] = races['year'].astype(int)
races['round'] = races['round'].astype(int)
races['circuitId'] = races['circuitId'].astype(int)

races.head()

,raceId,year,round,circuitId,name,date,time,url
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...

In [ ]:
races.info()
races.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   raceId     997 non-null    int64
 1   year       997 non-null    int64
 2   round      997 non-null    int64
 3   circuitId  997 non-null    int64
 4   name       997 non-null    object
 5   date       997 non-null    datetime64[ns]
 6   time       997 non-null    object
 7   url        997 non-null    object
dtypes: datetime64[ns](1), int64(4), object(3)
memory usage: 62.4+ KB

,raceId,year,round,circuitId,name,date,time,url
count,997.000000,997.000000,997.000000,997.000000,997,997,997,997
unique,NaN,NaN,NaN,NaN,42,NaN,21,997
top,NaN,NaN,NaN,NaN,British Grand Prix,NaN,Unknown,http://en.wikipedia.org/wiki/2018_Abu_Dhabi_Gr...
freq,NaN,NaN,NaN,NaN,69,NaN,731,1
mean,500.034102,1988.990973,8.233701,21.762287,NaN,1989-07-05 17:51:41.705115264,NaN,NaN
min,1.000000,1950.000000,1.000000,1.000000,NaN,1950-05-13 00:00:00,NaN,NaN
25%,250.000000,1974.000000,4.000000,9.000000,NaN,1974-10-06 00:00:00,NaN,NaN
50%,499.000000,1990.000000,8.000000,18.000000,NaN,1990-10-21 00:00:00,NaN,NaN
75%,748.000000,2005.000000,12.000000,30.000000,NaN,2005-09-25 00:00:00,NaN,NaN
max,1009.000000,2018.000000,21.000000,73.000000,NaN,2018-11-25 00:00:00,NaN,NaN
std,289.590656,18.906633,4.884669,16.437073,NaN,NaN,NaN,NaN

### Result

The races dataset has been successfully cleaned and standardized. Missing values were handled, duplicate rows removed, date fields corrected, and data formats improved. The dataset is now ready for analysis and visualization.

## Cleaning results.csv

This section performs data cleaning and preprocessing for the results dataset. The file contains Formula 1 race result records including driver standings, finishing positions, lap data, points earned, and race status.

In [ ]:
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22.0,1,1.0,1,1,10.0,58,34:50.6,5690616.0,39.0,2.0,01:27.5,218.3,1
1,2,18,2,2,3.0,5,2.0,2,2,8.0,58,5.478,5696094.0,41.0,3.0,01:27.7,217.586,1
2,3,18,3,3,7.0,7,3.0,3,3,6.0,58,8.163,5698779.0,41.0,5.0,01:28.1,216.719,1
3,4,18,4,4,5.0,11,4.0,4,4,5.0,58,17.181,5707797.0,58.0,7.0,01:28.6,215.464,1
4,5,18,5,1,23.0,3,5.0,5,5,4.0,58,18.014,5708630.0,43.0,1.0,01:27.4,218.385,1

In [ ]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23777 entries, 0 to 23776
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         23777 non-null  int64
 1   raceId           23777 non-null  int64
 2   driverId         23777 non-null  int64
 3   constructorId    23777 non-null  int64
 4   number           23771 non-null  float64
 5   grid             23777 non-null  int64
 6   position         13227 non-null  float64
 7   positionText     23777 non-null  object
 8   positionOrder    23777 non-null  int64
 9   points           23777 non-null  float64
 10  laps             23777 non-null  int64
 11  time             6004 non-null   object
 12  milliseconds     6003 non-null   float64
 13  fastestLap       5383 non-null   float64
 14  rank             5531 non-null   float64
 15  fastestLapTime   5383 non-null   object
 16  fastestLapSpeed  5383 non-null   object
 17  statusId         23777 non-null  int64
dtypes: float64(6), int64(8), object(4)
memory usage: 3.3+ MB

In [ ]:
results.isnull().sum()

resultId               0
raceId                 0
driverId               0
constructorId          0
number                 6
grid                   0
position           10550
positionText           0
positionOrder          0
points                 0
laps                   0
time               17773
milliseconds       17774
fastestLap         18394
rank               18246
fastestLapTime     18394
fastestLapSpeed    18394
statusId               0
dtype: int64

In [ ]:
results.duplicated().sum()

np.int64(0)

### Cleaning Process

The dataset is checked for missing values, duplicate rows, inconsistent formatting, and incorrect data types. Numeric fields are standardized and missing values are handled for smoother analysis.

In [ ]:
# Clean column names
results.columns = results.columns.str.strip()

# Remove duplicate rows
results.drop_duplicates(inplace=True)

# Handle missing values properly

# Text columns
results['time'].fillna("Unknown", inplace=True)
results['fastestLapTime'].fillna("Unknown", inplace=True)

# Numeric columns
results['number'].fillna(0, inplace=True)
results['position'].fillna(0, inplace=True)
results['milliseconds'].fillna(0, inplace=True)
results['fastestLap'].fillna(0, inplace=True)
results['rank'].fillna(0, inplace=True)
results['points'].fillna(0, inplace=True)

# Fastest lap speed (best to use median)
results['fastestLapSpeed'] = pd.to_numeric(results['fastestLapSpeed'], errors='coerce')
results['fastestLapSpeed'].fillna(results['fastestLapSpeed'].median(), inplace=True)

# Convert numeric columns
results['resultId'] = results['resultId'].astype(int)
results['raceId'] = results['raceId'].astype(int)
results['driverId'] = results['driverId'].astype(int)
results['constructorId'] = results['constructorId'].astype(int)
results['number'] = results['number'].astype(int)
results['grid'] = results['grid'].astype(int)
results['position'] = results['position'].astype(int)
results['positionOrder'] = results['positionOrder'].astype(int)
results['laps'] = results['laps'].astype(int)
results['milliseconds'] = results['milliseconds'].astype(int)
results['fastestLap'] = results['fastestLap'].astype(int)
results['rank'] = results['rank'].astype(int)
results['statusId'] = results['statusId'].astype(int)
results['points'] = results['points'].astype(float)

results.head()

/tmp/ipykernel_3731/1735369462.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['time'].fillna("Unknown", inplace=True)
/tmp/ipykernel_3731/1735369462.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['fastestLapTime'].fillna("Unknown", inplace=True)
/tmp/ipykernel_3731/1735369462.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['number'].fillna(0, inplace=True)
/tmp/ipykernel_3731/1735369462.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['position'].fillna(0, inplace=True)
/tmp/ipykernel_3731/1735369462.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['milliseconds'].fillna(0, inplace=True)
/tmp/ipykernel_3731/1735369462.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['fastestLap'].fillna(0, inplace=True)
/tmp/ipykernel_3731/1735369462.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['rank'].fillna(0, inplace=True)
/tmp/ipykernel_3731/1735369462.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['points'].fillna(0, inplace=True)
/tmp/ipykernel_3731/1735369462.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  results['fastestLapSpeed'].fillna(results['fastestLapSpeed'].median(), inplace=True)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,34:50.6,5690616,39,2,01:27.5,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,5.478,5696094,41,3,01:27.7,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,8.163,5698779,41,5,01:28.1,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,17.181,5707797,58,7,01:28.6,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,18.014,5708630,43,1,01:27.4,218.385,1

In [ ]:
results.info()
results.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23777 entries, 0 to 23776
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         23777 non-null  int64
 1   raceId           23777 non-null  int64
 2   driverId         23777 non-null  int64
 3   constructorId    23777 non-null  int64
 4   number           23777 non-null  int64
 5   grid             23777 non-null  int64
 6   position         23777 non-null  int64
 7   positionText     23777 non-null  object
 8   positionOrder    23777 non-null  int64
 9   points           23777 non-null  float64
 10  laps             23777 non-null  int64
 11  time             23777 non-null  object
 12  milliseconds     23777 non-null  int64
 13  fastestLap       23777 non-null  int64
 14  rank             23777 non-null  int64
 15  fastestLapTime   23777 non-null  object
 16  fastestLapSpeed  23777 non-null  float64
 17  statusId         23777 non-null  int64
dtypes: float64(2), int64(13), object(3)
memory usage: 3.3+ MB

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
count,23777.000000,23777.000000,23777.000000,23777.000000,23777.000000,23777.000000,23777.000000,23777,23777.000000,23777.000000,23777.000000,23777,2.377700e+04,23777.000000,23777.000000,23777,23777.000000,23777.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39,NaN,NaN,NaN,5759,NaN,NaN,NaN,552,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,Unknown,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8517,NaN,NaN,NaN,17773,NaN,NaN,NaN,18394,NaN,NaN
mean,11889.481053,487.203937,226.515961,46.281785,16.961181,11.270303,4.329226,NaN,13.081591,1.601403,45.270598,NaN,1.591403e+06,9.296169,2.465492,NaN,45.439325,18.242293
std,6864.691322,269.904857,231.386102,56.174091,13.645737,7.346436,5.241633,NaN,7.824711,3.665154,30.525404,NaN,2.871793e+06,19.024675,5.404102,NaN,84.616228,26.380824
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,0.000000,NaN,0.000000e+00,0.000000,0.000000,NaN,0.000000,1.000000
25%,5945.000000,273.000000,55.000000,6.000000,7.000000,5.000000,0.000000,NaN,7.000000,0.000000,20.000000,NaN,0.000000e+00,0.000000,0.000000,NaN,0.000000,1.000000
50%,11889.000000,478.000000,154.000000,25.000000,15.000000,11.000000,2.000000,NaN,13.000000,0.000000,52.000000,NaN,0.000000e+00,0.000000,0.000000,NaN,0.000000,11.000000
75%,17833.000000,718.000000,314.000000,57.000000,23.000000,17.000000,8.000000,NaN,19.000000,1.000000,66.000000,NaN,4.468659e+06,0.000000,0.000000,NaN,0.000000,16.000000
max,23781.000000,988.000000,843.000000,210.000000,208.000000,34.000000,33.000000,NaN,39.000000,50.000000,200.000000,NaN,1.509054e+07,78.000000,24.000000,NaN,257.320000,136.000000

### Result

The results dataset has been successfully cleaned and standardized. Duplicate records were removed, missing values handled, and numeric columns corrected. The dataset is now ready for analysis and visualization.

## Cleaning seasons.csv

This section performs data cleaning and preprocessing for the seasons dataset. The file contains Formula 1 season information including season year and related reference links.

In [ ]:
seasons.head()

   year                                                url
0  2009  http://en.wikipedia.org/wiki/2009_Formula_One_...
1  2008  http://en.wikipedia.org/wiki/2008_Formula_One_...
2  2007  http://en.wikipedia.org/wiki/2007_Formula_One_...
3  2006  http://en.wikipedia.org/wiki/2006_Formula_One_...
4  2005  http://en.wikipedia.org/wiki/2005_Formula_One_...

In [ ]:
seasons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    69 non-null     int64
 1   url     69 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.2+ KB

In [ ]:
seasons.isnull().sum()

year    0
url     0
dtype: int64

In [ ]:
seasons.duplicated().sum()

np.int64(0)

### Cleaning Process

The dataset is checked for missing values, duplicate rows, incorrect data types, and inconsistent formatting. The year column is converted into integer format for accurate chronological analysis.

In [ ]:
# Clean column names
seasons.columns = seasons.columns.str.strip()

# Remove duplicate rows
seasons.drop_duplicates(inplace=True)

# Fill missing values
seasons.fillna("Unknown", inplace=True)

# Convert year column
seasons['year'] = seasons['year'].astype(int)

# Show cleaned data
seasons.head()

   year                                                url
0  2009  http://en.wikipedia.org/wiki/2009_Formula_One_...
1  2008  http://en.wikipedia.org/wiki/2008_Formula_One_...
2  2007  http://en.wikipedia.org/wiki/2007_Formula_One_...
3  2006  http://en.wikipedia.org/wiki/2006_Formula_One_...
4  2005  http://en.wikipedia.org/wiki/2005_Formula_One_...

In [ ]:
seasons.info()
seasons.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    69 non-null     int64
 1   url     69 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.2+ KB

               year                                                url
count     69.000000                                                 69
unique          NaN                                                 69
top             NaN  http://en.wikipedia.org/wiki/2009_Formula_One_...
freq            NaN                                                  1
mean    1984.000000                                                NaN
std       20.062403                                                NaN
min     1950.000000                                                NaN
25%     1967.000000                                                NaN
50%     1984.000000                                                NaN
75%     2001.000000                                                NaN
max     2018.000000                                                NaN

### Result

The seasons dataset has been successfully cleaned and standardized. Duplicate rows were removed, missing values handled, and the year column was corrected. The dataset is now ready for analysis and visualization.

## Cleaning status.csv

This section performs data cleaning and preprocessing for the status dataset. The file contains Formula 1 race result status descriptions such as finished, accident, engine failure, disqualified, and other race outcomes.

In [ ]:
status.head()

   statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

In [ ]:
status.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   statusId  134 non-null    int64
 1   status    134 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.2+ KB

In [ ]:
status.isnull().sum()

statusId    0
status      0
dtype: int64

In [ ]:
status.duplicated().sum()

np.int64(0)

### Cleaning Process

The dataset is checked for missing values, duplicate rows, inconsistent formatting, and incorrect data types. Text values are standardized to improve readability and consistency.

In [ ]:
# Standardize column names
status.columns = status.columns.str.strip()

# Remove duplicate rows
status.drop_duplicates(inplace=True)

# Fill missing values
status.fillna("Unknown", inplace=True)

# Standardize text formatting
status['status'] = status['status'].str.strip().str.title()

# Convert numeric column
status['statusId'] = status['statusId'].astype(int)

status.head()

   statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

In [ ]:
status.info()
status.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   statusId  134 non-null    int64
 1   status    134 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.2+ KB

          statusId    status
count   134.000000       134
unique         NaN       134
top            NaN  Finished
freq           NaN         1
mean     68.708955       NaN
std      39.660178       NaN
min       1.000000       NaN
25%      34.250000       NaN
50%      69.500000       NaN
75%     102.750000       NaN
max     136.000000       NaN

### Result

The status dataset has been successfully cleaned and standardized. Duplicate rows were removed, missing values handled, text values formatted consistently, and data types corrected. The dataset is now ready for analysis and visualization.

## Export Cleaned CSV Files

In [ ]:
# Export cleaned datasets to CSV files

pit.to_csv("cleaned_pitStops.csv", index=False)
qual.to_csv("cleaned_qualifying.csv", index=False)
races.to_csv("cleaned_races.csv", index=False)
results.to_csv("cleaned_results.csv", index=False)
seasons.to_csv("cleaned_seasons.csv", index=False)
status.to_csv("cleaned_status.csv", index=False)